import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "./fonts";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {" "}
        <div className="main-nav-bg">
          <Header />
        </div>
        {children}
        <footer>
          <div className="container flex footer-container">
            <div>
              <a href="#" className="company-logo">
                <img src="./assets/asset 1.png" alt="company logo" />
              </a>

              <p>
                Ellis bridge, Ahmedabad Gujarat, <br />
                380006
              </p>
              <p>+91-8286168403</p>
              <p>contact@mayostack.in</p>
              <div className="flex footer-icons">
                <img src="./assets/instagram.svg" className="contact-icon" />
                <img src="./assets/linkedin.png" className="contact-icon" />
                <img src="./assets/threads.svg" className="contact-icon" />
              </div>
            </div>
            <div className="link-column flex">
              <h4>Services</h4>
              <a href="#" className="hover-link">
                Web Application
              </a>
              <a href="#" className="hover-link">
                Full Stack Development
              </a>
              <a href="#" className="hover-link">
                MERN Stack Development
              </a>
              <a href="#" className="hover-link">
                Testing & QA Services
              </a>
              <a href="#" className="hover-link">
                UI/UX Design Services
              </a>
            </div>
            <div className="link-column flex">
              <h4>Company</h4>
              <a href="#" className="hover-link">
                About Us
              </a>
              <a href="#" className="hover-link">
                Careers
              </a>
              <a href="#" className="hover-link">
                Blogs
              </a>
              <a href="#" className="hover-link">
                Portfolio
              </a>
              <a href="#" className="hover-link">
                Contact Us
              </a>
            </div>
          </div>
        </footer>
        <div className="subfooter">
          <div className="container flex subfooter-container">
            Copyright © 2024 Mayostack Infosolutions Pvt Ltd. All Rights
            Reserved
          </div>
        </div>
      </body>
    </html>
  );
}
